# Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [12]:
import pandas as pd

In [27]:
ratings = pd.read_csv('ratings.csv')

filt_ratings = ratings[(ratings['rating'] == 5.0)]
total_five = filt_ratings.groupby('movieId').count()
total_five.sort_values(by = ['rating'], ascending=[False]).head(1)

         userId  rating  timestamp
movieId
318         153     153        153

# Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [28]:
data = pd.read_csv('power.csv')
data.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [34]:
data[data['country'].str.contains('lat', case = False) ]['country'].unique()

filt_data =  data[ ((data['country'] == 'Latvia') | 
                        (data['country'] == 'Lithuania') |
                        (data['country'] == 'Estonia')) & 
                      ((data['year'] >= 2005) &  (data['year'] <= 2010)) &
                      ((data['category'] == 4) | 
                        (data['category'] == 12) |
                        (data['category'] == 21)) &
                      (data['quantity'] >= 0)
                     ]
total = filt_data['quantity'].sum()
print(total)

240580.0

# Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [36]:
new_data = pd.read_html('https://www.finam.ru/quotes/stocks/russia/?utm_source=yandex_direct_POISK&utm_medium=cpc&utm_term=rynok_akcij&utm_content=ad_8623879632|ph_19685106538|pst_premium|ps_1|dev_desktop&utm_campaign=trafik_finam&yclid=1459357338355132328')

In [41]:
new_data[0]

,Unnamed: 0,Инструмент,"Посл. сделка, ₽",% Изм. цены,Открытие,Макс.,Мин.,Закрытие,"Объем, шт.",Время обн.
0,NaN,СбербанкПотенциал:+42%,191.4 ₽,4.38%,193.300,194.6200,189.1000,183.370,52 028 150,24.03 13:08
1,NaN,ЛУКОЙЛ,4476.5 ₽,7.21%,4500.000,4550.0000,4362.5000,4175.500,1 126 751,24.03 13:08
2,NaN,ГАЗПРОМ ао,175.17 ₽,4.05%,174.390,176.7100,172.6100,168.350,41 427 230,24.03 13:08
3,NaN,ГМКНорНик,18742 ₽,15.41%,17336.000,18860.0000,17100.0000,16240.000,536 032,24.03 13:08
4,NaN,Магнит аоПотенциал:+41%,3056 ₽,2.34%,3040.000,3085.0000,3009.5000,2986.000,291 230,24.03 13:22
5,NaN,АЛРОСА аоПотенциал:+114%,61.4 ₽,6.67%,60.440,62.0000,58.7500,57.560,15 366 210,24.03 13:22
6,NaN,Роснефть,296.25 ₽,8.12%,300.000,301.2500,285.4500,274.000,12 887 620,24.03 13:22
7,NaN,АэрофлотПотенциал:+30%,68.1 ₽,8.61%,66.000,68.9000,65.0400,62.700,25 711 220,24.03 13:22
8,NaN,СевСт-ао,830.4 ₽,4.64%,813.800,834.6000,809.4000,793.600,827 226,24.03 13:22
9,NaN,МосБиржаПотенциал:+22%,94.24 ₽,2.88%,93.430,94.9500,93.0100,91.600,5 404 300,24.03 13:08
10,NaN,+МосЭнергоПотенциал:-3%,1.76 ₽,4.45%,1.753,1.7975,1.7135,1.685,18 579 000,24.03 13:08
11,NaN,AGRO-гдр,554.2 ₽,6.05%,532.000,565.6000,527.0000,522.600,51 633,24.03 13:22
12,NaN,ENPL-гдр,571 ₽,4.73%,545.200,580.0000,541.0000,545.200,10 533,24.03 13:18
13,NaN,ETLN-гдр,104,1.64%,104.580,108.6400,100.0000,102.320,284 849,24.03 13:20
14,NaN,FIVE-гдр,2127 ₽,2.98%,2098.000,2258.0000,2095.5000,2065.500,269 616,24.03 13:08
15,NaN,iАвиастКао,0.4485 ₽,3.58%,0.433,0.4500,0.4180,0.433,858 000,24.03 13:11
16,NaN,iДонскЗР,2012 ₽,6.46%,1918.000,2014.0000,1906.0000,1890.000,13,24.03 11:27
17,NaN,iДонскЗР п,1380 ₽,2.99%,1320.000,1380.0000,1320.0000,1340.000,7,24.03 12:45
18,NaN,iИСКЧ ао,11.35 ₽,5.88%,10.250,11.5700,10.2000,10.720,23 200,24.03 13:05
19,NaN,iММЦБ ао,735.5,0.41%,740.500,741.0000,735.5000,732.500,5,24.03 12:43
20,NaN,iНПОНаука,153 ₽,3.38%,149.800,153.0000,149.8000,148.000,730,24.03 13:06
21,NaN,iФармсинтз,6.655 ₽,7.69%,6.230,7.1900,6.2300,6.180,1 934 600,24.03 13:20
22,NaN,iQIWI,838.5 ₽,4.88%,819.500,839.5000,816.0000,799.500,25 396,24.03 13:22
23,NaN,Polymetal,1153.8 ₽,12.57%,1053.100,1164.0000,1052.4000,1025.000,637 122,24.03 13:08
24,NaN,Raven,27.4 ₽,0%,29.200,29.8000,24.6000,27.400,32 600,24.03 13:01
25,NaN,RUSAL plc,23.125 ₽,7.08%,22.400,23.1700,22.2050,21.595,16 672 760,24.03 13:22
26,NaN,TCS-гдр,970.8,5.04%,972.000,1010.0000,934.6000,924.200,181 048,24.03 13:08
27,NaN,Yandex clA,2431.6 ₽,5.73%,2363.000,2448.2000,2363.0000,2299.800,475 446,24.03 13:08
28,NaN,АбрауДюрсо,132.5 ₽,3.52%,126.500,133.5000,126.0000,128.000,2 990,24.03 13:07
29,NaN,Авангрд-ао,620 ₽,1.64%,615.000,620.0000,600.0000,610.000,113,24.03 13:16